version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alphine
    tty: true
    ports:
      - "15672:15672"
      - "5672:5672"
    custom-rabbitmq:
      image: custom-rabbitmq:1.0
      container_name: custom-rabbitmq
      hostname: custom-rabbitmq
      ports:
        - "5673:5673"
        - "15672:15672"
      restart: always
        